#!/bin/sh
RUBYINC=`ruby -r mkmf -e 'print Config::CONFIG["archdir"]'`
RUBYLIB=`ruby -r mkmf -e 'print Config::CONFIG["LIBRUBYARG_SHARED"]'`

gcc -fPIC -I${RUBYINC} -g -O2 -c librubyocamlsearchr.c -o main.o

gcc -shared -o librubyocamlsearchr.so main.o libocamlsearchr.so ${RUBYLIB}
