#!/bin/sh
ocamlopt -c -dtypes relative_search.ml
ocamlopt -c -dtypes search_manager.ml
ocamlopt -c -dtypes relative_search_stub.ml
ocamlopt -output-obj -o search.o relative_search.cmx search_manager.cmx relative_search_stub.cmx

