#!/bin/sh
RUBYINC=`ruby -r mkmf -e 'print Config::CONFIG["archdir"]'`
gcc -fPIC -I${RUBYINC} -g -O2  -c librubyocamlsearchr.c -o main.o
gcc -shared -o librubyocamlsearchr.so main.o libocamlsearchr.so -lc
